version: '2'
services:
  box:
    image: busybox
    volumes:
      - /box
  database:
    image: mongo:3.0.14
    volumes:
      - /data/db
    ports:
      - '27017:27017'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/miniweather
    volumes_from:
      - box
    ports:
      - "3000:3000"
    links:
      - database
