development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: miniweather_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= Settings.mongodb.dev.host %>
      options:
  # Configure Mongoid specific options. (optional)
  options:

test:
  clients:
    default:
      database: miniweather_test
      hosts:
        - <%= Settings.mongodb.dev.host %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
