weather_api:
  host: 'http://api.openweathermap.org/data/2.5/'
  weather_query_path: 'weather?q='
  weather_city_id_path: 'weather?id='
  weather_coordinates_lat_path: 'weather?lat='
  weather_coordinates_lon_path: '&lon='
  units_query: '&units='
  icon_full_path: 'http://openweathermap.org/img/w/'
mongodb:
  dev:
    host: 192.168.99.100:27017
